### ISSUE TITLE
Questions about _step_slice in line 285 of layers.py

### ISSUE THREAD

**Issue by jinfengfeng** [nyu-dl/dl4mt-multi#1]
Hi!

I have two quesitons:
1. The _step_slice function have 15 arguments listed in its definition, while len(sequences)+len(outputs_info)+len(non_sequences) is 17. Why?
2. _step_slice returns h, ctx_, alpha.T, why ctx_ and alpha.T will not disturb enc_ls, cc_ (arguments) ?

**Comment by orhanf** [comment]
Hi @jinfengfeng, you should not count the `None` elements in the `outputs_info` since they are not going to appear in the arguments list and in our case, `None` values are used as placeholders for `ctx_` and `alpha.T`. 

Please check the `outputs_info` section in `scan` documentation, [here](http://deeplearning.net/software/theano/library/scan.html)

**Comment by jinfengfeng** [comment]
Thanks! @orhanf
