### ISSUE TITLE
Issues related to validation

### ISSUE THREAD

**Issue by jayparks** [nyu-dl/dl4mt-multi#3]
Hi thanks for sharing great work.

i'm trying to train multi-way model but encountered some issues related to intermediate validation.

first one is that the code never executes bleu validation.

i properly set 'bleu_val_freq' and 'bleu_script' config but nothing happens, validation is just skipped.

the second one is about log_prob_freq.

computing log probability on val set is executed at every log_prob_freq i specified, but it outputs error like this:

Traceback (most recent call last):
  File "train_mlnmt.py", line 25, in <module>
    get_logprob_streams(config))
  File "/home/pjh/dl4mt-multi/mlnmt.py", line 152, in train
    main_loop.run()
  File "/home/pjh/dl4mt-multi/mcg/algorithm.py", line 328, in run
    reraise_as(e)
  File "/home/pjh/codes/blocks/blocks/utils/**init**.py", line 225, in reraise_as
    six.reraise(type(new_exc), new_exc, orig_exc_traceback)
  File "/home/pjh/dl4mt-multi/mcg/algorithm.py", line 314, in run
    while self._run_epoch():
  File "/home/pjh/dl4mt-multi/mcg/algorithm.py", line 352, in _run_epoch
    while self._run_iteration():
  File "/home/pjh/dl4mt-multi/mcg/algorithm.py", line 374, in _run_iteration
    self._run_extensions('after_batch', batch)
  File "/home/pjh/dl4mt-multi/mcg/algorithm.py", line 382, in _run_extensions
    extension.dispatch(CallbackName(method_name), *args)
  File "/home/pjh/codes/blocks/blocks/extensions/__init__.py", line 328, in dispatch
    self.do(callback_invoked, *(from_main_loop + tuple(arguments)))
  File "/home/pjh/dl4mt-multi/mcg/extensions.py", line 375, in do
    if numpy.isnan(numpy.mean(probs[cg_name])):
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 2885, in mean
    out=out, keepdims=keepdims)
  File "/usr/local/lib/python2.7/dist-packages/numpy/core/_methods.py", line 72, in _mean
    ret = ret / rcount
TypeError: unsupported operand type(s) for /: 'list' and 'int'

Original exception:
    TypeError: unsupported operand type(s) for /: 'list' and 'int'

it seems numpy related issue, my numpy version is 1.11.0

Other than these, sampling_freq, save_freq and actual training works fine.
Any ideas or comments would be appreciated! FYI i'm attaching my configurations.

config['normalized_bleu'] = True
config['track_n_models'] = 3
config['output_val_set'] = True
config['beam_size'] = 12

config['log_prob_freq'] = 20
config['lob_prob_bs'] = 10

config['reload'] = True
config['save_freq'] = 25000
config['sampling_freq'] = 2500
config['bleu_val_freq'] = 25
config['val_burn_in'] = 1
config['finish_after'] = 2000000
config['incremental_dump'] = True

**Comment by orhanf** [comment]
HI @JayParks , thank you for pointing these out. Let me answer them one by one:
1. `bleu_val_freq` is actually a legacy option, which is ignored completely (as you've observed). The reason why we do not evaluate BLEU during training is because it takes quite a bit of time and training pauses during decoding. So I removed this functionality to make code less dilated. What I do for BLEU evaluation is, calling `evaluate_models.py` script while the model is actually training. It runs on CPU and evaluates models (on BLEU) as they are saved by the training main loop. By doing so, you do not pause training to do evaluation. I'd suggest you to take a look at `evaluate_models.py` script. If you still want to use BLEU validation functionality during training, you can take a look at [this](https://github.com/mila-udem/blocks-examples/blob/master/machine_translation/sampling.py#L115-L290) example and adapt it respectively (let me know if you decide to do so, i can outline more instructions).
2. This is an old bug that i fixed but apparently forgot to push to this repo. The problem is about the batch sizes during validation. `log_prob_bs` should divide the number of lines in the validation set without remainder, else, it raises this error :) The fix is very easy, and i will push as soon as i can (i'm travelling atm).

**Comment by jayparks** [comment]
Ah i see. I've tried evaluate_models.py and it works like a charm!
Appreciate your quick reply during holiday :)

**Comment by orhanf** [comment]
@JayParks, now we allow arbitrary batch sizes for logprob streams, with c0342a0 and by default batch size is 100.
